esphome:
  name: dual-jkibms-dashboard
  friendly_name: Акумулятори

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: "Ta2"
  password: "09122004"

logger:
  level: WARN
  logs:
    esp32_ble: ERROR
    ble_client: ERROR
    jkbms: WARN
    mqtt: WARN

api:

ota:
  - platform: esphome

mqtt:
  broker: broker.hivemq.com
  port: 1883
  topic_prefix: "jkbms_ta2"

esp32_ble:

ble_client:
  - mac_address: "98:DA:F0:0A:E9:85"
    id: jkbms_dev_1
  - mac_address: "A4:C1:38:0F:3A:D5"
    id: jkbms_dev_2

jkbms:
  - ble_client_id: jkbms_dev_1
    id: my_jkbms_1
    update_interval: 5s
  - ble_client_id: jkbms_dev_2
    id: my_jkbms_2
    update_interval: 5s

sensor:
  # ================= 40 (bms1) =================
  - platform: jkbms
    jkbms_id: my_jkbms_1
    total_voltage:
      name: "4️⃣0️⃣ Напруга"
      id: bms1_total_voltage
    current:
      name: "4️⃣0️⃣ Струм"
      id: bms1_current
    power:
      name: "4️⃣0️⃣ Потужність"
      id: bms1_power
    soc:
      name: "4️⃣0️⃣ SOC"
      id: bms1_soc
    capacity_remaining:
      name: "4️⃣0️⃣ Залишок"
      id: bms1_capacity_remaining
    delta_cell_voltage:
      name: "4️⃣0️⃣ Дельта"
      id: bms1_delta
    min_cell_voltage:
      name: "4️⃣0️⃣ Мін. комірка"
    max_cell_voltage:
      name: "4️⃣0️⃣ Макс. комірка"
    charging_power_tube_temperature:
      name: "4️⃣0️⃣ MOSFET M"
    temperature_1:
      name: "4️⃣0️⃣ Термодатчик 1"
    temperature_2:
      name: "4️⃣0️⃣ Термодатчик 2"
    cell_1_voltage:
      name: "4️⃣0️⃣ Комірка 1"
    cell_2_voltage:
      name: "4️⃣0️⃣ Комірка 2"
    cell_3_voltage:
      name: "4️⃣0️⃣ Комірка 3"
    cell_4_voltage:
      name: "4️⃣0️⃣ Комірка 4"
    cell_5_voltage:
      name: "4️⃣0️⃣ Комірка 5"
    cell_6_voltage:
      name: "4️⃣0️⃣ Комірка 6"
    cell_7_voltage:
      name: "4️⃣0️⃣ Комірка 7"
    cell_8_voltage:
      name: "4️⃣0️⃣ Комірка 8"

  # ================= 100 (bms2) =================
  - platform: jkbms
    jkbms_id: my_jkbms_2
    total_voltage:
      name: "1️⃣0️⃣0️⃣ Напруга"
      id: bms2_total_voltage
    current:
      name: "1️⃣0️⃣0️⃣ Струм"
      id: bms2_current
    power:
      name: "1️⃣0️⃣0️⃣ Потужність"
      id: bms2_power
    soc:
      name: "1️⃣0️⃣0️⃣ SOC"
      id: bms2_soc
    capacity_remaining:
      name: "1️⃣0️⃣0️⃣ Залишок"
      id: bms2_capacity_remaining
    delta_cell_voltage:
      name: "1️⃣0️⃣0️⃣ Дельта"
      id: bms2_delta
    min_cell_voltage:
      name: "1️⃣0️⃣0️⃣ Мін. комірка"
    max_cell_voltage:
      name: "1️⃣0️⃣0️⃣ Макс. комірка"
    charging_power_tube_temperature:
      name: "1️⃣0️⃣0️⃣ MOSFET M"
    temperature_1:
      name: "1️⃣0️⃣0️⃣ Термодатчик 1"
    temperature_2:
      name: "1️⃣0️⃣0️⃣ Термодатчик 2"
    cell_1_voltage:
      name: "1️⃣0️⃣0️⃣ Комірка 1"
    cell_2_voltage:
      name: "1️⃣0️⃣0️⃣ Комірка 2"
    cell_3_voltage:
      name: "1️⃣0️⃣0️⃣ Комірка 3"
    cell_4_voltage:
      name: "1️⃣0️⃣0️⃣ Комірка 4"
    cell_5_voltage:
      name: "1️⃣0️⃣0️⃣ Комірка 5"
    cell_6_voltage:
      name: "1️⃣0️⃣0️⃣ Комірка 6"
    cell_7_voltage:
      name: "1️⃣0️⃣0️⃣ Комірка 7"
    cell_8_voltage:
      name: "1️⃣0️⃣0️⃣ Комірка 8"

text_sensor:
  # Динамічні індикатори заряду для обох батарей
  - platform: template
    name: "4️⃣0️⃣ Рівень заряду"
    id: bms1_status_icon
    lambda: |-
      float soc = id(bms1_soc).state;
      if (soc > 80) {
        return {"🟢  ( >80% )"};
      } else if (soc > 60) {
        return {"🔵 ( 61-80% )"};
      } else if (soc > 40) {
        return {"🟡 ( 41-60% )"};
      } else if (soc > 20) {
        return {"🟠 ( 21-40% )"};
      } else {
        return {"🔴 ( <=20% )"};
      }
    update_interval: 10s

  - platform: template
    name: "1️⃣0️⃣0️⃣ Рівень заряду"
    id: bms2_status_icon
    lambda: |-
      float soc = id(bms2_soc).state;
      if (soc > 80) {
        return {"🟢  ( >80% )"};
      } else if (soc > 60) {
        return {"🔵 ( 61-80% )"};
      } else if (soc > 40) {
        return {"🟡 ( 41-60% )"};
      } else if (soc > 20) {
        return {"🟠 ( 21-40% )"};
      } else {
        return {"🔴 ( <=20% )"};
      }
    update_interval: 10s

switch:
  # ================= 40 вимикачі =================
  - platform: jkbms
    jkbms_id: my_jkbms_1
    charging:
      name: "⚡4️⃣0️⃣ Заряд"
      id: bms1_charging_switch
    discharging:
      name: "⚡4️⃣0️⃣ Розряд"
      id: bms1_discharging_switch
    balancer:
      name: "⚖️4️⃣0️⃣ Балансир"
      id: bms1_balancer_switch

  # ================= 100 вимикачі =================
  - platform: jkbms
    jkbms_id: my_jkbms_2
    charging:
      name: "⚡1️⃣0️⃣0️⃣ Заряд"
      id: bms2_charging_switch
    discharging:
      name: "⚡1️⃣0️⃣0️⃣ Розряд"
      id: bms2_discharging_switch
    balancer:
      name: "⚖️1️⃣0️⃣0️⃣ Балансир"
      id: bms2_balancer_switch

button:
  - platform: jkbms
    jkbms_id: my_jkbms_1
    shutdown:
      name: "🌙4️⃣0️⃣ Вимкнути (Сон)"
    reset:
      name: "💫4️⃣0️⃣ Перезавантажити"

  - platform: jkbms
    jkbms_id: my_jkbms_2
    shutdown:
      name: "🌙1️⃣0️⃣0️⃣ Вимкнути (Сон)"
    reset:
      name: "💫1️⃣0️⃣0️⃣ Перезавантажити"

mqtt:
  on_json_message:
    - topic: "jkbms_ta2/command/bat40/charging"
      then:
        - lambda: |-
            if (payload.as<std::string>() == "ON") {
              id(bms1_charging_switch).turn_on();
            } else if (payload.as<std::string>() == "OFF") {
              id(bms1_charging_switch).turn_off();
            }
    - topic: "jkbms_ta2/command/bat40/discharging"
      then:
        - lambda: |-
            if (payload.as<std::string>() == "ON") {
              id(bms1_discharging_switch).turn_on();
            } else if (payload.as<std::string>() == "OFF") {
              id(bms1_discharging_switch).turn_off();
            }
    - topic: "jkbms_ta2/command/bat40/balancer"
      then:
        - lambda: |-
            if (payload.as<std::string>() == "ON") {
              id(bms1_balancer_switch).turn_on();
            } else if (payload.as<std::string>() == "OFF") {
              id(bms1_balancer_switch).turn_off();
            }

    - topic: "jkbms_ta2/command/bat100/charging"
      then:
        - lambda: |-
            if (payload.as<std::string>() == "ON") {
              id(bms2_charging_switch).turn_on();
            } else if (payload.as<std::string>() == "OFF") {
              id(bms2_charging_switch).turn_off();
            }
    - topic: "jkbms_ta2/command/bat100/discharging"
      then:
        - lambda: |-
            if (payload.as<std::string>() == "ON") {
              id(bms2_discharging_switch).turn_on();
            } else if (payload.as<std::string>() == "OFF") {
              id(bms2_discharging_switch).turn_off();
            }
    - topic: "jkbms_ta2/command/bat100/balancer"
      then:
        - lambda: |-
            if (payload.as<std::string>() == "ON") {
              id(bms2_balancer_switch).turn_on();
            } else if (payload.as<std::string>() == "OFF") {
              id(bms2_balancer_switch).turn_off();
            }
